autoupload/urls.py
from django.conf.urls import patterns, url
from autoupload import views


urlpatterns = patterns(
    '',
    # samples page
    url(r'^samples/$',
        views.samples, name='samples'),

    # web homepage page
    url(r'^web/$',
        views.webteeinsight, name='webteeinsight'),

    # autoupload pages
    # default (vi)
    url(r'^autoupload/$',
        views.autoupload_vi, name='autoupload'),
    url(r'^autoupload/subscribe/$',
        views.subscribe_vi, name='autoupload_subscribe'),
    url(r'^autoupload/subscribe/thanks/$',
        views.subscribe_tks_vi, name='autoupload_subscribe_thanks'),
    # en
    url(r'^autoupload-en/$',
        views.autoupload, name='autoupload_en'),
    url(r'^autoupload-en/subscribe/$',
        views.subscribe, name='autoupload_subscribe_en'),
    url(r'^autoupload-en/subscribe/thanks/$',
        views.subscribe_tks, name='autoupload_subscribe_thanks_en'),
    # vi
    url(r'^autoupload-vi/$',
        views.autoupload_vi, name='autoupload_vi'),
    url(r'^autoupload-vi/subscribe/$',
        views.subscribe_vi, name='autoupload_subscribe_vi'),
    url(r'^autoupload-vi/subscribe/thanks/$',
        views.subscribe_tks_vi, name='autoupload_subscribe_thanks_vi'),

    # api subscribe for autoupload page
    url(r'^api/subscribe-autoupload/$',
        views.APISubscribeAutoUpload.as_view(), name='api_subscribe_autoupload'),
    url(r'^api/check-email/$',
        views.APICheckEmailSubscribeAU.as_view(), name='api_check_email_sau'),

)

teeproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()
# The page_not_found() view is overridden by handler404:
handler404 = 'teeinsight.views.teeinsight_page_not_found'
# The server_error() view is overridden by handler500:
handler500 = 'teeinsight.views.teeinsight_error'
# The permission_denied() view is overridden by handler403:
handler403 = 'teeinsight.views.teeinsight_permission_denied'
# The bad_request() view is overridden by handler400:
handler400 = 'teeinsight.views.teeinsight_bad_request'

urlpatterns = patterns(
    '',
    url(r'^$', 'autoupload.views.autoupload_vi', name='home'),

    url(r'^(?i)media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'', include('authentication.urls')),

    url(r'', include('autoupload.urls')),

    url(r'', include('teeinsight.urls')),
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += patterns(
        '',
        url(r'^(?i)debug/', include(debug_toolbar.urls)),
    )

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)


class RegistrationForm(forms.Form):
    username = forms.RegexField(
        regex=r'^\w+$',
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Username"),
        error_messages={'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Email address"))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password"))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data


class ExpandRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(ExpandRegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already used")
        return data

teeinsight/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ValidationError


class EmailAuthenticationForm(AuthenticationForm):
    def clean_username(self):
        username = self.data['username']
        if '@' in username:
            try:
                username = User.objects.get(email=username).username
            except ObjectDoesNotExist:
                raise ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
        return username


class RegistrationForm(forms.Form):
    username = forms.RegexField(
        regex=r'^\w+$',
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Username"),
        error_messages={'invalid': _("This value must contain only letters, numbers and underscores.")})
    email = forms.EmailField(
        widget=forms.TextInput(attrs=dict(required=True, max_length=30)),
        label=_("Email address"))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password"))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)),
        label=_("Password (again)"))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. Please try another one."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

templates/webteeinsight/detail_content.html
{% load staticfiles %}
{% load filters %}
<div class="wrapper">
    {#    <div class="row">#}
    <div class="wrapper-content detail-content">
        {% include 'webteeinsight/detail_content_info_boxs.html' %}

        {% include 'webteeinsight/detail_content_flow.html' %}

        {% include 'webteeinsight/detail_content_plans.html' %}

        {#            {% include 'webteeinsight/detail_content_testimonial_faq.html' %}#}

        {% include 'webteeinsight/detail_content_contact_map.html' %}
    </div>
    {#    </div>#}

    <div class="clear"></div>
</div>

templates/webteeinsight/detail_content_contact_map.html
{% load staticfiles %}
{% load filters %}

<div class="row">
    <div class="col-md-12">
        <div class="content detail-contact-map" id="contact-us">
            <div class="row">
                <div class="col-md-7" data-0="left: -200%" data-4200="left: -200%; position:relative;"
                     data-4600="left: 0;transition:all 0.5s 0s;-webkit-transition:all 0.5s 0s;">
                    <form class="contact-form">
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   id="id_sender" name="sender" placeholder="Your name">
                        </div>
                        <div class="form-group">
                            <input type="tel" class="form-control"
                                   id="id_telephone" name="telephone" placeholder="Telephone">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control"
                                   id="id_email" name="email" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" rows="14"
                                      id="id_message" name="message" placeholder="Message"></textarea>
                        </div>
                        <button type="reset" class="btn btn-default">Clear</button>
                        <button type="submit" class="btn btn-default">Send</button>
                    </form>
                </div>
                <div class="col-md-5" data-0="right: -200%" data-4200="right: -200%; position:relative;"
                     data-4600="right: 0;transition:all 0.5s 0s;-webkit-transition:all 0.5s 0s;">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3607.7642683184677!2d106.67234051471382!3d10.808031361565167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752920c1660543%3A0x7004b05b8cf39221!2zMTU4LTE1OEEgxJDDoG8gRHV5IEFuaCwgcGjGsOG7nW5nIDksIFBow7ogTmh14bqtbiwgSOG7kyBDaMOtIE1pbmgsIFZp4buHdCBOYW0!5e1!3m2!1svi!2sus!4v1471258756714"
                            width="375" height="375" frameborder="0" style="border:0" allowfullscreen></iframe>
                    <div class="row detail-address">
                        <address class="col-md-6 text-left">
                            <strong>Gia Thy Building</strong><br/>
                            158 Dao Duy Anh Str.<br/>
                            Phu Nhuan Dist, HCMC.
                        </address>
                        {% comment %}
                        <address class="col-md-6 text-left">
                            +84 937 355 440<br/>
                            +84 123 366 300<br/>
                            <a href="mailto:info@teeinsight.com">info@teeinsight.com</a><br/>
                            <a href="mailto:@teeinsight.support">@teeinsight.support</a>
                        </address>
                        {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/webteeinsight/detail_content_info_boxs.html
{% load staticfiles %}
{% load filters %}

<div class="row" id="about">
    <div class="col-md-12">
        <div class="content">
            <div class="row" id="about-us">
                <div class="col-md-3 text-center info-box" data-0="opacity: 0;"
                     data-50="opacity: 0; transform: scale(0);"
                     data-700="opacity: 1; transform[bounce]: scale(1);transition:all 0.5s;-webkit-transition:all 0.5s">
                            <span class="info-icon about-us">
                                <img src="{% static 'images/web_teeinsight/about-us-gray.png' %}"/>
                            </span>

                    <div class="info-short-text">
                        <h3 class="info-title">About Us</h3>

                        <p>teeinsight is developed and powered by iTracker Corporation, an independent internet
                            data research company.</p>
                    </div>
                </div>
                <div class="col-md-3 text-center info-box" data-0="opacity: 0;"
                     data-50="opacity: 0; transform: scale(0);"
                     data-700="opacity: 1; transform[bounce]: scale(1); transition:all 0.5s;-webkit-transition:all 0.5s">
                    <span class="info-icon our-services">
                        <img src="{% static 'images/web_teeinsight/our-services-gray.png' %}"/>
                    </span>

                    <div class="info-short-text">
                        <h3 class="info-title">Our Services</h3>

                        <p>teeinsight is the data insights platform for online tee &amp; accessories sellers to
                            catch up in-time with the market campaigns and convey the ideas for successful
                            campaigns from every piece of data value.</p>
                    </div>
                </div>
                <div class="col-md-3 text-center info-box" data-0="opacity: 0;"
                     data-50="opacity: 0; transform: scale(0);"
                     data-700="opacity: 1; transform[bounce]: scale(1); left: 0px;transition:all 0.5s;-webkit-transition:all 0.5s">
                            <span class="info-icon our-product">
                                <img src="{% static 'images/web_teeinsight/our-product-gray.png' %}"/>
                            </span>

                    <div class="info-short-text">
                        <h3 class="info-title">Our Product</h3>

                        <p>Our product is composed of sets of data values from all key crowded platforms as:
                            teespring.com, viralstyle.com, teezily.com, gearlaunch.com, ...</p>
                    </div>
                </div>
                <div class="col-md-3 text-center info-box" data-0="opacity: 0;"
                     data-50="opacity: 0; transform: scale(0);"
                     data-700="opacity: 1; transform[bounce]: scale(1); left: 0px;transition:all 0.5s;-webkit-transition:all 0.5s">
                                <span class="info-icon why-us">
                                    <img src="{% static 'images/web_teeinsight/why-us-gray.png' %}"/>
                                </span>

                    <div class="info-short-text">
                        <h3 class="info-title">Why Us</h3>

                        <p>We are the independent research entity. Thus, we are always and only looking into
                            the most valued data insights for the sake of your business, and that is our
                            business.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/webteeinsight/detail_content_plans.html
{% load staticfiles %}
{% load filters %}

<div class="row">
    <div id="pricing" class="col-md-12" data-0="opacity: 0"
         data-3600="display:block; opacity:0; position:relative; top:25px"
         data-3900="opacity:1;transition:all 0.5s;-webkit-transition:all 0.5s;">
        <div class="content detail-plans">
            <h1>GET STARTED & PRICING</h1>

            <div class="row plan-packs">
                <div class="col-md-4 plan-pack">
                    <span class="plan-icon"><img src="{% static 'images/web_teeinsight/star_0.png' %}"/></span>

                    <div class="plan-card">
                        <div class="plan-card-header">
                            <h1>Free</h1>
                            <span>Proin sagittis nibh</span>
                        </div>
                        <div class="plan-card-body">
                            <ul class="plan-features">
                                <li>- Access to all campaigns.</li>
                                <li>- Get updated with constant new campaigns.</li>
                                <li>- Social statistical data for evaluating the campaigns performance.</li>
                                <li>- Key websites data trends by demographics in key markets.</li>
                                <li>- Free Of Charge (FOC) for updated data scales more data insights development in the
                                    future.
                                </li>
                            </ul>
                            <span class="plan-price">Free</span>
                        </div>
                        <div class="plan-card-footer">
                            <a href="{% url 'register' %}" class="btn btn-default btn-block button" type="submit">
                                Sign Up
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 plan-pack">
                    <span class="plan-icon"><img src="{% static 'images/web_teeinsight/star_05.png' %}"/></span>

                    <div class="plan-card">
                        <div class="plan-card-header">
                            <h1>Lite</h1>
                            <span>Vivamus Adispicing</span>
                        </div>
                        <div class="plan-card-body">
                            <ul class="plan-features">
                                <li>- Access to all campaigns.</li>
                                <li>- Get updated with constant new campaigns.</li>
                                <li>- Social statistical data for evaluating the campaigns performance.</li>
                                <li>- Key websites data trends by demographics in key markets.</li>
                                <li>- Free Of Charge (FOC) for updated data scales more data insights development in the
                                    future.
                                </li>
                            </ul>
                            <span class="plan-price">$29<sup class="top">99</sup><small> /mo</small></span>
                        </div>
                        <div class="plan-card-footer">
                            <a href="{% url 'register' %}" class="btn btn-default btn-block button" type="submit">
                                Sign Up
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 plan-pack">
                    <span class="plan-icon"><img src="{% static 'images/web_teeinsight/star_1.png' %}"/></span>

                    <div class="plan-card">
                        <div class="plan-card-header">
                            <h1>Full Platform</h1>
                            <span>You Get Everything!</span>
                        </div>
                        <div class="plan-card-body">
                            <ul class="plan-features">
                                <li>- Access to all campaigns.</li>
                                <li>- Get updated with constant new campaigns.</li>
                                <li>- Social statistical data for evaluating the campaigns performance.</li>
                                <li>- Key websites data trends by demographics in key markets.</li>
                                <li>- Free Of Charge (FOC) for updated data scales more data insights development in the
                                    future.
                                </li>
                            </ul>
                            <span class="plan-price">$49<sup class="top">99</sup><small> /mo</small></span>
                        </div>
                        <div class="plan-card-footer">
                            <a href="{% url 'register' %}" class="btn btn-default btn-block button" type="submit">
                                Sign Up
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/webteeinsight/detail_content_testimonial_faq.html
{% load staticfiles %}
{% load filters %}

<div class="row">
    <div id="testimonial-faq" class="col-md-12" data-0="opacity: 0"
         data-4300="display:block; opacity:0; position:relative; top:25px"
         data-4600="opacity:1;transition:all 0.5s 0s;-webkit-transition:all 0.5s 0s;">
        <div class="content detail-testimonial-faq">
            <div class="row">
                <div class="col-md-6">
                    <h1>Testimonial</h1>
                    {% for testi in 3|get_range %}
                        <div class="detail-testimonial animated">
                            <img src="{% static 'images/user1-128x128.jpg' %}" alt="testimonial" class="img-circle"/>

                            <div class="testimonial-quote">
                                <a href="javascript:void(0)">@teeinsight</a> Sed ut perspiciatis unde omnis iste natus
                                error sit voluptatem
                                accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.
                                <span class="testimonial-name">Testimonial - CEO</span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-md-6">
                    <h1>FAQs</h1>
                    {% for testi in 3|get_range %}
                        <div class="detail-faq animated">
                            <a href="javascript:void(0)">This is Photoshop's version of Lorem Ipsum?</a>

                            <p>This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
                                Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis
                                sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi
                                accumsan ipsum velit.</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/webteeinsight/header_content.html
{% load staticfiles %}
<header class="main-header" id="main-header">
    <nav class="navbar navbar-static-top">
        <div class="navbar-header">
            <a href="{% url 'home' %}" class="navbar-brand logo-tee-insight">
                <img src="{% static 'images/logo_256x100.png' %}" class="img-responsive animated"/>
            </a>
        </div>

        <div class="navbar-custom-menu login-box animated">
            <ul class="nav navbar-nav animated">
                {% if user.is_authenticated %}
                    <li class="user user-menu">
                        <a href="{% url 'login' %}{% if next_url %}?next={{ next_url }}{% endif %}">
                            <img src="{% static 'images/icon_256.png' %}" class="user-image hidden-sm"
                                 alt="User Image">
                            <span>{{ user.username|default:'anonymous' }}</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            <i class="fa fa-fw fa-lock"></i>Sign Out
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}{% if next_url %}?next={{ next_url }}{% endif %}">
                            <i class="fa fa-fw fa-key fa-flip-horizontal"></i>Login
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}">
                            <i class="fa fa-fw fa-user"></i>Sign Up
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/webteeinsight/right_sidebar_content.html
{% load staticfiles %}
<div class="animated right-sidebar ">
    <header class="main-header sidebar-header animated">
        <nav class="navbar navbar-static-top">
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="javascript:void(0)" class="sidebar-toggle" sidebar_toggle role="button">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-3x fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="navbar-custom-menu login-box-res animated">
        <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
                <li class="user user-menu">
                    <a href="{% url 'login' %}{% if next_url %}?next={{ next_url }}{% endif %}">
                        <img src="{% static 'images/icon_256.png' %}" class="user-image hidden-xs"
                             alt="User Image">
                        <span>{{ user.username|default:'anonymous' }}</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">
                        <i class="fa fa-fw fa-lock"></i>Sign Out
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'login' %}{% if next_url %}?next={{ next_url }}{% endif %}">
                        <i class="fa fa-fw fa-key fa-flip-horizontal"></i>Login
                    </a>
                </li>
                <li>
                    <a href="{% url 'register' %}">
                        <i class="fa fa-fw fa-user"></i>Sign Up
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="sidebar-body" id="right-bar">
        <ul class="menu-custom">
            <li><a href="#about-us">About Us</a></li>
            <li><a href="#learn">Learn From Your Competitors</a></li>
            <li><a href="#idea">Find Ideas</a></li>
            <li><a href="#support">Support Your Campaigns</a></li>
            <li><a href="#analyze">Analyze Your Business</a></li>
            <li><a href="#aggregate">Aggregate Data and Compare</a></li>
            <li><a href="#alerts">Instant Alerts</a></li>
            <li><a href="#pricing">Pricing</a></li>
            {#<li><a href="#testimonial-faq">Testimonial and FAQ</a></li>#}
            <li><a href="#contact-us">Contact Us</a></li>
        </ul>
    </div>
    <ul class="menu-social">
        <li><a><i class="fa fa-2x fa-facebook"></i></a></li>
        <li><a><i class="fa fa-2x fa-google-plus"></i></a></li>
        <li><a><i class="fa fa-2x fa-skype"></i></a></li>
        <li><a><i class="fa fa-2x fa-linkedin"></i></a></li>
    </ul>
</div>

templates/webteeinsight/slide1_content.html
{% load staticfiles %}
<!--suppress ALL -->
<div class="wrapper item active">
    <div class="row">
        <div class="wrapper-content slide-content slide_1">
            <div class="teeinsight-title" mid-content>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.6em;">GROW</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.3em;">YOUR</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.1em;">BUSINESS</h1>

                <hr class="slideanimated slideInLeftSlider"/>

                <p class="text-black slideanimated slideInRightSlider" style="padding-right: 25%;">
                    <strong>teeinsight</strong>
                    – a place where all insights meet to grow ideas and thus, grow your business.</p>
                <a href="#pricing" type="button" role="try-it"
                   class="btn btn-lg btn-try btn-half-block slideanimated slideInRightSlider">
                    Try it<i class="fa fa-play"></i>
                </a>

            </div>
        </div>
    </div>

    <div class="clear"></div>
</div>

templates/webteeinsight/slide2_content.html
{% load staticfiles %}
<!--suppress ALL -->
<div class="wrapper item">
    <div class="row">
        <div class="wrapper-content slide-content slide_2">
            <div class="teeinsight-title" mid-content>
                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.6em;">PUSH</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.3em;">HARD</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.1em;">all limitations</h1>
                <hr class="slideanimated slideInLeftSlider"/>
                <p class="text-black slideanimated slideInRightSlider">
                    <strong>teeinsight</strong> – born to push hard all limitations for your sake of tee sales growth.
                </p>
                <a href="#pricing" type="button" role="try-it"
                   class="btn btn-lg btn-try btn-half-block slideanimated slideInRightSlider">
                    Try it<i class="fa fa-play"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="clear"></div>
</div>

templates/webteeinsight/slide3_content.html
{% load staticfiles %}
<!--suppress ALL -->
<div class="wrapper item">
    <div class="row">
        <div class="wrapper-content slide-content slide_3">
            <div class="teeinsight-title" mid-content>
                <h1 class="slideanimated slideInLeftSlider" style="margin-left: 0.6em;">ALONG</h1>

                <h1 class="slideanimated slideInLeftSlider" style="margin-left: 0.3em;">WITH</h1>

                <h1 class="slideanimated slideInLeftSlider" style="margin-left: 0.1em;">YOUR BUSINESS</h1>
                <hr class="slideanimated slideInLeftSlider"/>
                <p class=" slideanimated slideInRightSlider">
                    <strong>teeinsight</strong> – always along with your
                    business, always listen to your problem and help you out.</p>
                <a href="#pricing" type="button" role="try-it"
                   class="btn btn-lg btn-try btn-half-block  slideanimated slideInRightSlider">
                    Try it<i class="fa fa-play"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="clear"></div>
</div>

templates/webteeinsight/slide4_content.html
{% load staticfiles %}
<!--suppress ALL -->
<div class="wrapper item">
    <div class="row">
        <div class="wrapper-content slide-content slide_4">
            <div class="teeinsight-title" mid-content>
                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.6em;">Powered by</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.3em;">iTracker</h1>

                <h1 class="text-black slideanimated slideInLeftSlider" style="margin-left: 0.1em;">Corporation</h1>
                <hr class=" slideanimated slideInLeftSlider"/>
                <p class="text-black slideanimated slideInRightSlider">
                    <strong>teeinsight</strong> – independent and
                    dedicated research business, powered by iTracker Corporation.</p>
                <a href="#pricing" type="button" role="try-it"
                   class="btn btn-lg btn-try btn-half-block slideanimated slideInRightSlider">
                    Try it<i class="fa fa-play"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="clear"></div>
</div>